#!/usr/bin/python3
# SPDX-FilecopyrightText : 2023 Riki Ogata s20c1705pv@s.chibakoudai.jp
# SPDX-License-Identifier : BSD-3-Clause

import sys

ans1 =0.0
ans2 =0.0

for line in sys.stdin:
     ans1 += float(line)
    # ans2 -= float(line)

print(ans1)
# print(ans2)
