#!/usr/bin/python3
# SPDX-FilecopyrightText : 2023 Riki Ogata s20c1705pv@s.chibakoudai.jp
# SPDX-License-Identifier : BSD-3-Clause

import sys

ans1 =0
#ans2 =0

for line in sys.stdin:
     ans1 += int(line)
    # ans2 -= int(line)

print(ans1)
#print(ans2)
